### ISSUE TITLE
vgg16.t7 unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by fuddyduddy** [zhanghang1989/PyTorch-Style-Transfer#38]
It's been a while since the last vgg16 issue i found on this "Issues".

So i download the vgg16.t7 from the paper quoted in this github.
And i run this command "python main.py train --epochs 4 --style-folder images/ownstyles --save-model-dir own_models --cuda 1"
i have put the vgg16.t7 into models folder, it's been detected correctly. However, the following problem happened.

```
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    main()
  File "main.py", line 41, in main
    train(args)
  File "main.py", line 135, in train
    utils.init_vgg16(args.vgg_model_dir)
  File "C:\Users\user\Prepwork\Cap Project\PyTorch-Multi-Style-Transfer\experiments\utils.py", line 100, in init_vgg16
    vgglua = load_lua(os.path.join(model_folder, 'vgg16.t7'))
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'numpy.ndarray'
```

Is there anyway i can fix this? i found in other thread they said replace with another one, but i could not find another one other than from stanford.

Thanks!

**Comment by zhanghang1989** [comment]
Sorry that I am not actively maintaining this repo now.

I actually tried the code recently. The `MSG-Net` is still working with PyTorch 1.4.0.

**Comment by fuddyduddy** [comment]
Alright, thanks. I will close this issue now.

BTW, just tried downgrade to PyTorch 1.4.0. However, the following error comes up:
```
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    main()
  File "main.py", line 36, in main
    raise ValueError("ERROR: cuda is not available, try running on CPU")
ValueError: ERROR: cuda is not available, try running on CPU
```
It looks like need to downgrade CUDA as well. But i am not gonna try it further due to time constraints.
